#!/bin/bash

workspace=`hyprctl -j activeworkspace | jq '.id'`

function handler {
  if [[ ${1:0:9} == "workspace" ]]; then
    workspace=${1:11}
  fi

  if [[ ${1:0:11} == "closewindow" ]]; then
    windows=$(hyprctl workspaces -j | jq ".[] | select(.id == $workspace) | .windows")

    if [[ $windows > 1 || $windows == 0 ]]; then
      echo 'true'
    else
      echo 'false'
    fi
  fi

  # hyprctl clients update latency workaround
  if [[ ${1:0:11} == "closewindow" ]]; then
    sleep 1
    non_floating_windows=$(hyprctl -j clients | jq ".[] | select(.workspace.id == $workspace) | select(.floating == false) | 1" | wc -l)

    if [[ $non_floating_windows > 1 || $non_floating_windows == 0 ]]; then
      echo 'true'
    else
      echo 'false'
    fi

    return
  fi

  if [[ ${1:0:18} == "changefloatingmode" || ${1:0:9} == "workspace" || ${1:0:10} == "openwindow" ]]; then
    non_floating_windows=$(hyprctl -j clients | jq ".[] | select(.workspace.id == $workspace) | select(.floating == false) | 1" | wc -l)

    if [[ $non_floating_windows > 1 || $non_floating_windows == 0 ]]; then
      echo 'true'
    else
      echo 'false'
    fi

    return
  fi
}

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read event; do handler $event; done

