#!/usr/bin/env bash

case "$1" in
  default)
    hyprctl dispatch workspace 3

    kitty -1 yazi &
    sleep 1
    kitty -1 &
    sleep 1
    kitty -1 &

    sleep 1
    hyprctl --batch "dispatch workspace 1;"

    firefox-nightly &
    sleep 1
    firefox-nightly --new-window 'https://music.youtube.com' &
    sleep 1 
    firefox-nightly --new-window 'https://chatgpt.com/' &
    sleep 1
    firefox-nightly --new-window 'https://www.youtube.com/' &
    sleep 1
    firefox-nightly --new-window 'https://web.telegram.org/k' &

    sleep 1
    hyprctl --batch "dispatch resizewindowpixel exact 470 1187,title:ChatGPT ; dispatch resizewindowpixel exact 470 820,title:YouTube Music"

    hyprctl --batch "dispatch moveworkspacetomonitor workspace 1 1; dispatch workspace 2;"

    neovide &

    sleep 1
    hyprctl --batch "dispatch moveworkspacetomonitor workspace 1 1;"

    exit 0 ;;
  *)
    echo "Usage: $0 {workflow-name}" >&2
    exit 1 ;;
esac

