#!/bin/bash

BATTERY_STATUS_DIR=/sys/class/power_supply/BAT0

function echo-battery-status {
  echo "{\"percentage\": $(cat $BATTERY_STATUS_DIR/capacity), \"status\": \"$(cat $BATTERY_STATUS_DIR/status)\", \"time\": \"$(acpi | grep -Eo "([0-9]{2}:?){3}")\"}"
}

echo-battery-status
#acpi_listen | while read line; do echo-battery-status; done
