;; both are RegExp
tag_start = \^r
tag_end   = \^

;; x times image scaled down ; 1 mean original
quality   = 2

imagefile_script = scripts/get-wallpaper.sh

[const]
pr = '@V>li(0.3)'
bg = '@DM>da(.9)'
fg = '@LV>l(80)>de(0.3)'

[kitty]
filename = configs/kitty.conf
realfilepath = /home/careem/.config/kitty/kitty.conf

[eww]
filename = configs/eww_top-main.scss
realfilepath = /home/careem/.config/eww/bars/top-main/style.scss

[wofi]
filename = configs/wofi.css
realfilepath = /home/careem/.config/wofi/style.css

[firefox]
filename = configs/crawfox.css
realfilepath = /home/careem/.mozilla/firefox/13gd5xvd.default-release/chrome/resources/crawfox.au.css

[nvim]
filename = configs/nvim-colorscheme.lua
realfilepath = /home/careem/.config/nvim/lua/crawraps/plugins/catppuccin.lua
